### ISSUE TITLE
Release to include 2022 holidays ? 

### ISSUE THREAD

**Issue by arthurlutz** [opening-hours/opening_hours.js#434]
For the french region I get : 

```
[11.11.2022 11:43.03.691] [ERROR] An error occurred during evaluation of the value "Tu 16:15-18:30, We 10:00-12:30, We 13:30-18:30, Th 16:15-18:30, Fr 16:15-18:30, Sa 10:00-12:30, Sa 13:30-17:00; PH off; SH Tu 16:00-18:30, We 10:00-12:00, We 13:30-18:30, Th 10:00-12:00, Th 16:00-18:30, Fr 16:00-18:30". Please submit a pull request: https://github.com/opening-hours/opening_hours.js. School holiday not defined for the year 2022.
```

It seems that holidays for 2022 are in https://github.com/opening-hours/opening_hours.js/blob/master/src/holidays/fr.yaml#L390 

But maybe this is not included in the 3.7.0  release https://github.com/opening-hours/opening_hours.js/releases  ? 

Should there be a release for 2022 ? Maybe I can upgrade to master to get this working ?

**Comment by ypid** [comment]
https://github.com/opening-hours/opening_hours.js/blob/master/CHANGELOG.rst#v380---2022-05-18 has been released already I had just forgotten to add it to https://github.com/opening-hours/opening_hours.js/releases. I fixed that, sorry ;-) From https://github.com/arthurlutz/MMM-OpeningHours/blob/OSM/package.json I conclude that you just missed the latest release because of my mistake.

**Comment by arthurlutz** [comment]
Thanks for looking at this issue @ypid. I've upgraded but I still get the same error. 

The error can reproduced here : https://openingh.ypid.de/evaluation_tool/?EXP=Tu%2016%3A15-18%3A30%2C%20We%2010%3A00-12%3A30%2C%20We%2013%3A30-18%3A30%2C%20Th%2016%3A15-18%3A30%2C%20Fr%2016%3A15-18%3A30%2C%20Sa%2010%3A00-12%3A30%2C%20Sa%2013%3A30-17%3A00%3B%20PH%20off%3B%20SH%20Tu%2016%3A00-18%3A30%2C%20We%2010%3A00-12%3A00%2C%20We%2013%3A30-18%3A30%2C%20Th%2010%3A00-12%3A00%2C%20Th%2016%3A00-18%3A30%2C%20Fr%2016%3A00-18%3A30&lat=47.25554&lon=-1.51714&mode=0&DATE=1668422280000  

Any other ideas on how to fix this ?

**Comment by ypid** [comment]
The error message seems to be precise. I know that the code sometimes looks ahead into the next year. I would say it will work when SH for 2023 is defined for fr.
